version: 2
updates:
  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    directory: "/SpringBackups"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "develop"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "develop"
